In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.layers import Dense, LeakyReLU
from tensorflow.keras.activations import linear, relu, sigmoid
from tensorflow.keras.models import Sequential
from tensorflow.keras.losses import MeanSquaredError, BinaryCrossentropy

2023-10-20 11:11:48.419964: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
df_train = pd.read_csv("digitRecognizer/train.csv")
df_train = df_train.dropna()
df_train.describe()

label   pixel0   pixel1   pixel2   pixel3   pixel4   pixel5  \
count  42000.000000  42000.0  42000.0  42000.0  42000.0  42000.0  42000.0   
mean       4.456643      0.0      0.0      0.0      0.0      0.0      0.0   
std        2.887730      0.0      0.0      0.0      0.0      0.0      0.0   
min        0.000000      0.0      0.0      0.0      0.0      0.0      0.0   
25%        2.000000      0.0      0.0      0.0      0.0      0.0      0.0   
50%        4.000000      0.0      0.0      0.0      0.0      0.0      0.0   
75%        7.000000      0.0      0.0      0.0      0.0      0.0      0.0   
max        9.000000      0.0      0.0      0.0      0.0      0.0      0.0   

        pixel6   pixel7   pixel8  ...      pixel774      pixel775  \
count  42000.0  42000.0  42000.0  ...  42000.000000  42000.000000   
mean       0.0      0.0      0.0  ...      0.219286      0.117095   
std        0.0      0.0      0.0  ...      6.312890      4.633819   
min        0.0      0.0      0.0  ...      0.000000      0.000000   
25%        0.0      0.0      0.0  ...      0.000000      0.000000   
50%        0.0      0.0      0.0  ...      0.000000      0.000000   
75%        0.0      0.0      0.0  ...      0.000000      0.000000   
max        0.0      0.0      0.0  ...    254.000000    254.000000   

           pixel776     pixel777      pixel778      pixel779  pixel780  \
count  42000.000000  42000.00000  42000.000000  42000.000000   42000.0   
mean       0.059024      0.02019      0.017238      0.002857       0.0   
std        3.274488      1.75987      1.894498      0.414264       0.0   
min        0.000000      0.00000      0.000000      0.000000       0.0   
25%        0.000000      0.00000      0.000000      0.000000       0.0   
50%        0.000000      0.00000      0.000000      0.000000       0.0   
75%        0.000000      0.00000      0.000000      0.000000       0.0   
max      253.000000    253.00000    254.000000     62.000000       0.0   

       pixel781  pixel782  pixel783  
count   42000.0   42000.0   42000.0  
mean        0.0       0.0       0.0  
std         0.0       0.0       0.0  
min         0.0       0.0       0.0  
25%         0.0       0.0       0.0  
50%         0.0       0.0       0.0  
75%         0.0       0.0       0.0  
max         0.0       0.0       0.0  

[8 rows x 785 columns]

In [3]:
df_train.head(5)

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [4]:
X = df_train.iloc[:,1:].to_numpy()
y = (df_train[["label"]]).to_numpy()

print("X shape: ", X.shape)
print("X: ", X[0:5,:])
print("y shape: ", y.shape)
print("y: ", y[0:5])

X shape:  (42000, 784)
X:  [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
y shape:  (42000, 1)
y:  [[1]
 [0]
 [1]
 [4]
 [0]]


In [24]:
tf.random.set_seed(1234)  # applied to achieve consistent results

initial_input_quantity = X.shape[0]

model = Sequential(
    [
    
        Dense(2000, activation='relu', name = 'layer1'),
        Dense(1000, activation='relu', name = 'layer2'),
        Dense(700, activation='relu', name = 'layer3'),
        Dense(500, activation='relu', name = 'layer4'),
        Dense(250, activation='relu', name = 'layer5'),
        Dense(125, activation='relu', name = 'layer6'),
        Dense(62, activation='relu', name = 'layer7'),
        Dense(10, activation = 'linear', name = "output")
     ]
)

model.compile(
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),  #<-- Note
    optimizer=tf.keras.optimizers.Adam(0.001),
)

model.fit(
    X,y,
    epochs=10
)

Epoch 1/10
1313/1313 [==============================] - 22s 16ms/step - loss: 0.5858
Epoch 2/10
1313/1313 [==============================] - 22s 17ms/step - loss: 0.1744
Epoch 3/10
1313/1313 [==============================] - 21s 16ms/step - loss: 0.1485
Epoch 4/10
1313/1313 [==============================] - 21s 16ms/step - loss: 0.1412
Epoch 5/10
1313/1313 [==============================] - 21s 16ms/step - loss: 0.1226
Epoch 6/10
1313/1313 [==============================] - 21s 16ms/step - loss: 0.1068
Epoch 7/10
1313/1313 [==============================] - 21s 16ms/step - loss: 0.1070
Epoch 8/10
1313/1313 [==============================] - 21s 16ms/step - loss: 0.0809
Epoch 9/10
1313/1313 [==============================] - 21s 16ms/step - loss: 0.0843
Epoch 10/10
1313/1313 [==============================] - 21s 16ms/step - loss: 0.0906


In [25]:
test_metrics = model.evaluate(X, y)
print("Metrics on test data:", test_metrics)

1313/1313 [==============================] - 2s 2ms/step - loss: 0.0473
Metrics on test data: 0.04730246961116791


In [27]:
predictions = model.predict(X)
sm_predictions = tf.nn.softmax(predictions).numpy()

m = X.shape[0]

predction_values = np.zeros(m)

for i in range(m):
    predction_values[i] = np.argmax(sm_predictions[i])

err = 0

for i in range(m):
    if(i%1000 == 0):
        print("Real label: %d" %y[i])
        print("Predction:  %d" %predction_values[i])
    if(y[i] != predction_values[i]):
        err+=1

print("Err: ", err)

1313/1313 [==============================] - 2s 1ms/step
Real label: 1
Predction:  1
Real label: 1
Predction:  1
Real label: 3
Predction:  3
Real label: 7
Predction:  7
Real label: 8
Predction:  8
Real label: 8
Predction:  8
Real label: 1
Predction:  1
Real label: 4
Predction:  4
Real label: 8
Predction:  8
Real label: 7
Predction:  7
Real label: 2
Predction:  2
Real label: 2
Predction:  2
Real label: 7
Predction:  7
Real label: 3
Predction:  3
Real label: 6
Predction:  6
Real label: 1
Predction:  1
Real label: 1
Predction:  1
Real label: 4
Predction:  4
Real label: 7
Predction:  7
Real label: 4
Predction:  4
Real label: 3
Predction:  3
Real label: 6
Predction:  6
Real label: 7
Predction:  7
Real label: 9
Predction:  9
Real label: 4
Predction:  4
Real label: 9
Predction:  9
Real label: 1
Predction:  1
Real label: 2
Predction:  2
Real label: 3
Predction:  3
Real label: 1
Predction:  1
Real label: 3
Predction:  3
Real label: 7
Predction:  7
Real label: 6
Predction:  6
Real label: 8
Predc